import React, { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "motion/react";
import { 
  Compass, 
  MapPin, 
  Maximize2, 
  Calendar, 
  Sparkles, 
  ChevronRight, 
  Phone, 
  Mail, 
  Layers, 
  Award, 
  Sliders, 
  Eye, 
  ArrowLeft, 
  ArrowRight, 
  Check, 
  Building2, 
  Trees, 
  Briefcase, 
  Maximize, 
  Cpu, 
  Palette, 
  Hammer, 
  Sun, 
  Moon, 
  MessageSquare,
  HelpCircle,
  Clock,
  ShieldCheck,
  FileText
} from "lucide-react";

// Image Paths generated by AI or pre-existing
const heroImg = "/src/assets/images/architect_hero_brutal_1784304683414.jpg";
const livingImg = "/src/assets/images/architect_living_concrete_1784304696597.jpg";
const blueprintImg = "/src/assets/images/architect_blueprint_model_1784304708296.jpg";

// Before image placeholder (using luxury beach house or a stylish tinted fallback)
const beforeImg = "/src/assets/images/luxury_mansion_sp_1784137092375.jpg";

interface Project {
  id: string;
  title: string;
  category: "Residencial" | "Corporativo" | "Interiores";
  location: string;
  year: string;
  area: string;
  materials: string[];
  description: string;
  image: string;
  concept: string;
}

export default function ArchitectPortfolio({ onBack }: { onBack?: () => void }) {
  const [activeCategory, setActiveCategory] = useState<"Todos" | "Residencial" | "Corporativo" | "Interiores">("Todos");
  const [selectedProject, setSelectedProject] = useState<Project | null>(null);
  
  // Before & After Slider State
  const [sliderPosition, setSliderPosition] = useState(50);
  const sliderRef = useRef<HTMLDivElement>(null);
  const [isDragging, setIsDragging] = useState(false);

  // Moodboard Interactive State
  const [selectedFloor, setSelectedFloor] = useState<"marmore" | "carvalho" | "cimento">("carvalho");
  const [selectedWall, setSelectedWall] = useState<"freijo" | "concreto" | "tijolo">("concreto");
  const [selectedLighting, setSelectedLighting] = useState<"dia" | "crepusculo" | "foco">("crepusculo");

  // Cost Estimator State
  const [area, setArea] = useState(150);
  const [typology, setTypology] = useState<"residencial" | "comercial" | "interiores">("residencial");
  const [finishLevel, setFinishLevel] = useState<"contemporaneo" | "atelie" | "brutalista">("atelie");
  const [extras, setExtras] = useState({
    automation: true,
    landscape: false,
    lighting: true
  });

  // Lead Form States
  const [formData, setFormData] = useState({
    name: "",
    email: "",
    phone: "",
    about: "",
    estimatedBudget: "r$ 200k - 500k",
  });
  const [formSubmitted, setFormSubmitted] = useState(false);

  // Before/After slider dragging logic
  const handleMove = (clientX: number) => {
    if (!sliderRef.current) return;
    const rect = sliderRef.current.getBoundingClientRect();
    const x = clientX - rect.left;
    const percentage = Math.max(0, Math.min(100, (x / rect.width) * 100));
    setSliderPosition(percentage);
  };

  const handleTouchMove = (e: React.TouchEvent) => {
    if (e.touches[0]) {
      handleMove(e.touches[0].clientX);
    }
  };

  const handleMouseMove = (e: React.MouseEvent) => {
    if (isDragging) {
      handleMove(e.clientX);
    }
  };

  useEffect(() => {
    const handleMouseUp = () => setIsDragging(false);
    window.addEventListener("mouseup", handleMouseUp);
    return () => window.removeEventListener("mouseup", handleMouseUp);
  }, []);

  // Moodboard configuration definitions
  const floorOptions = {
    marmore: { name: "Mármore Nero Marquina", color: "bg-[#1A1A1A] border-stone-800", text: "Textura fria e veios brancos marcantes sobre fundo escuro absoluto. Confere sofisticação monolítica incomparável e nobreza clássica." },
    carvalho: { name: "Carvalho Europeu Natural", color: "bg-[#C4A482] border-amber-200", text: "Garante aconchego térmico, veios orgânicos amadeirados e uma atmosfera escandinava minimalista de extrema elegância e calmaria." },
    cimento: { name: "Cimento Queimado Platinado", color: "bg-[#8E9091] border-slate-400", text: "Aparência industrial contemporânea, contínua e sem rejuntes. Ideal para ressaltar a honestidade estrutural dos espaços." }
  };

  const wallOptions = {
    freijo: { name: "Painéis Frisados em Freijó", texture: "bg-[#AA7A44]", text: "Madeira nativa de tonalidade média e brilho discreto. Proporciona excelente absorção acústica e refinamento visual ao living." },
    concreto: { name: "Concreto Ripado Aparente", texture: "bg-[#6B7280]", text: "Formas de madeira gravadas no concreto bruto de alta densidade. Textura tátil brutalista que serve como peça escultural central." },
    tijolo: { name: "Tijolo de Olaria Inglês Manual", texture: "bg-[#8B5A2B]", text: "Cerâmica moldada artesanalmente com variações rústicas de queima. Traz memórias afetivas, calor térmico e contraste geométrico único." }
  };

  const lightingOptions = {
    dia: { name: "Iluminação Natural Difusa (12:00)", icon: Sun, text: "Claridade abundante refletida por claraboias e panos de vidro zenitais. Enfatiza as cores reais e a pureza dos volumes geométricos." },
    crepusculo: { name: "Luz Quente Recessiva (18:30)", icon: Moon, text: "Sancas lineares de LED 2700K integradas aos detalhes arquitetônicos. Cria sombras suaves, mistério relaxante e uma experiência de descanso acolhedora." },
    foco: { name: "Pontos de Foco Minimalistas", icon: Compass, text: "Micro-spots em trilho eletrificado embutido em preto fosco. Iluminação pontual direcionada a obras de arte e texturas de parede específicas." }
  };

  // Projects database
  const projects: Project[] = [
    {
      id: "casa-origami",
      title: "Casa Origami nos Jardins",
      category: "Residencial",
      location: "São Paulo, SP",
      year: "2025",
      area: "780 m²",
      materials: ["Concreto Ripado", "Madeira Cumaru", "Mármore Travertino"],
      description: "Construída com base em dobras geométricas estruturais que desafiam a gravidade. A residência possui balanços de concreto de 8 metros sem pilares e grandes panos de vidro que dissolvem as barreiras entre o interior e o jardim interno planejado.",
      concept: "Concreto aparente monolítico que abraça a topografia natural, criando pátios protegidos de vento e ruído urbano.",
      image: livingImg
    },
    {
      id: "pavilhao-floresta",
      title: "Pavilhão da Floresta Ateliê",
      category: "Residencial",
      location: "Campos do Jordão, SP",
      year: "2024",
      area: "340 m²",
      materials: ["Aço Corten", "Vidro Duplo", "Pedra Moledo"],
      description: "Um refúgio de montanha suspenso sobre uma base de rocha basáltica local. Projetado de forma sustentável para minimizar a pegada no solo da mata nativa, utilizando energia solar passiva e madeira certificada em toda a estrutura do forro.",
      concept: "Fusão de materiais pesados e brutos (pedra e aço oxidado) com a leveza e transparência total do vidro térmico.",
      image: heroImg
    },
    {
      id: "sede-carbono",
      title: "Sede Corporativa Carbono",
      category: "Corporativo",
      location: "Faria Lima, SP",
      year: "2025",
      area: "1.200 m²",
      materials: ["Alumínio Escovado", "Lajes Alveolares", "Jardins Verticais"],
      description: "Sede de um fundo financeiro de vanguarda projetada sob o selo LEED Gold de eficiência energética. Conta com um átrio central com iluminação zenital de três pavimentos e painéis divisórios acústicos inteligentes revestidos em lã de PET reciclado.",
      concept: "Distribuição espacial fluida com foco no bem-estar corporativo, ventilação cruzada mecânica controlada por sensores e biofilia ativa.",
      image: blueprintImg
    },
    {
      id: "apartamento-brutal",
      title: "Apartamento Higienópolis",
      category: "Interiores",
      location: "São Paulo, SP",
      year: "2024",
      area: "210 m²",
      materials: ["Granilite Cinza", "Laminado Freijó", "Aço Carbono"],
      description: "Reforma total de apartamento modernista da década de 1960. As paredes internas divisórias foram totalmente demolidas para expor os pilares e vigas de concreto originais do prédio, contrapostos com painéis curvos de marcenaria sob medida.",
      concept: "Resgate histórico-arquitetônico integrando a materialidade crua original a elementos modernos, industriais e esculturais.",
      image: beforeImg
    }
  ];

  const filteredProjects = activeCategory === "Todos" 
    ? projects 
    : projects.filter(p => p.category === activeCategory);

  // Viability Estimator calculation logic
  const calculateEstimate = () => {
    let pricePerMeter = 1100; // base design & engineering architect fee per m²

    if (typology === "comercial") pricePerMeter += 350;
    if (typology === "interiores") pricePerMeter -= 150;

    if (finishLevel === "atelie") pricePerMeter += 400;
    if (finishLevel === "brutalista") pricePerMeter += 900;

    let extrasCost = 0;
    if (extras.automation) extrasCost += 15000;
    if (extras.landscape) extrasCost += 18000;
    if (extras.lighting) extrasCost += 12000;

    const designFee = Math.round(area * pricePerMeter);
    const estimatedBuildCost = Math.round(area * (finishLevel === "contemporaneo" ? 3800 : finishLevel === "atelie" ? 5200 : 7500));
    const projectDurationMonths = Math.ceil(area > 500 ? 8 : area > 200 ? 5 : 3);

    return {
      designFee: designFee.toLocaleString("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 }),
      buildCost: estimatedBuildCost.toLocaleString("pt-BR", { style: "currency", currency: "BRL", maximumFractionDigits: 0 }),
      months: projectDurationMonths,
      ratePerMeter: pricePerMeter
    };
  };

  const estimateResult = calculateEstimate();

  const handleLeadSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setFormSubmitted(true);
  };

  const shareToWhatsapp = () => {
    const formattedText = `Olá MÖBIUS Arq! Gostaria de conversar sobre um projeto:\n\n` +
      `- Nome: ${formData.name || "Interessado"}\n` +
      `- Área Estimada: ${area} m²\n` +
      `- Tipologia: ${typology.toUpperCase()}\n` +
      `- Padrão de Acabamento: ${finishLevel.toUpperCase()}\n` +
      `- Extras: ${Object.entries(extras).filter(([_, val]) => val).map(([key]) => key === "automation" ? "Automação" : key === "landscape" ? "Paisagismo" : "Projeto Luminotécnico").join(", ")}`;
    
    const url = `https://wa.me/5515997118125?text=${encodeURIComponent(formattedText)}`;
    window.open(url, "_blank");
  };

  return (
    <div className="min-h-screen bg-[#0A0C10] text-stone-200 font-sans selection:bg-amber-500/20 selection:text-amber-400 overflow-x-hidden relative">
      
      {/* Background elegant architectural layout grids */}
      <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.015)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.015)_1px,transparent_1px)] bg-[size:50px_50px] pointer-events-none" />
      <div className="absolute top-0 right-0 w-[500px] h-[500px] bg-amber-500/5 rounded-full blur-[120px] pointer-events-none" />
      <div className="absolute bottom-1/4 left-0 w-[600px] h-[600px] bg-stone-900/40 rounded-full blur-[140px] pointer-events-none" />

      {/* Floating Header */}
      <header className="fixed top-0 left-0 right-0 h-20 bg-[#0A0C10]/80 backdrop-blur-md border-b border-white/5 z-40 transition-all">
        <div className="max-w-7xl mx-auto h-full px-6 md:px-12 flex items-center justify-between">
          
          {/* Logo brand */}
          <div 
            onClick={() => {
              if (onBack) onBack();
            }}
            className="flex items-center space-x-3 cursor-pointer group"
          >
            <div className="h-9 w-9 border border-amber-500/40 flex items-center justify-center relative rounded">
              <Compass className="h-5 w-5 text-amber-500 group-hover:rotate-45 transition-transform duration-500" />
              <span className="absolute -bottom-1 -right-1 text-[8px] font-mono text-amber-500 font-bold bg-[#0A0C10] px-0.5 leading-none">M</span>
            </div>
            <div className="text-left">
              <span className="font-mono text-base font-black tracking-[0.25em] text-white block uppercase leading-none group-hover:text-amber-400 transition-colors">
                MÖBIUS
              </span>
              <span className="text-[9px] font-mono tracking-widest text-white/50 block uppercase">
                ARQUITETURA AUTORAL
              </span>
            </div>
          </div>

          {/* Desktop Nav menu */}
          <nav className="hidden md:flex items-center space-x-8 font-mono text-xs">
            <a href="#filosofia" className="text-white/60 hover:text-white transition-colors uppercase">Filosofia</a>
            <a href="#antes-depois" className="text-white/60 hover:text-white transition-colors uppercase">Renovação</a>
            <a href="#moodboard" className="text-white/60 hover:text-white transition-colors uppercase">Ateliê Material</a>
            <a href="#obras" className="text-white/60 hover:text-white transition-colors uppercase">Projetos</a>
            <a href="#viabilidade" className="text-amber-500/80 hover:text-amber-400 transition-colors uppercase flex items-center gap-1.5 font-bold">
              <Sliders className="h-3 w-3 animate-pulse" /> Simular Custo
            </a>
          </nav>

          {/* Quick Contact controls */}
          <div className="flex items-center space-x-3">
            {onBack && (
              <button
                type="button"
                onClick={onBack}
                className="hidden lg:flex items-center space-x-1.5 px-3.5 py-1.5 rounded border border-white/10 bg-white/5 hover:bg-white/10 text-white/80 font-mono text-xs transition-all cursor-pointer"
              >
                <ArrowLeft className="h-3.5 w-3.5" />
                <span>Voltar</span>
              </button>
            )}

            <a
              href="https://wa.me/5515997118125"
              target="_blank"
              rel="noreferrer"
              className="px-4 py-2.5 rounded bg-gradient-to-r from-amber-500 to-yellow-600 text-black font-mono text-xs font-black tracking-wide uppercase transition-all duration-300 transform hover:scale-[1.02] shadow-[0_0_15px_rgba(245,158,11,0.2)] flex items-center gap-1.5 cursor-pointer"
            >
              <Phone className="h-3.5 w-3.5" />
              <span className="hidden sm:inline">Falar com Arquiteto</span>
              <span className="inline sm:hidden">WhatsApp</span>
            </a>
          </div>

        </div>
      </header>

      {/* Hero Section */}
      <section className="pt-36 pb-24 md:py-40 relative z-10 overflow-hidden" id="hero">
        
        {/* Subtle coordinate markers in corners of stage */}
        <div className="absolute top-28 left-6 md:left-12 font-mono text-[9px] text-white/20 tracking-wider">LAT 23° 32' 51'' S // LONG 46° 38' 10'' W</div>
        <div className="absolute top-28 right-6 md:right-12 font-mono text-[9px] text-white/20 tracking-wider">MÖBIUS STUDIO // V.2026</div>

        <div className="max-w-7xl mx-auto px-6 md:px-12 grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          
          {/* Left Block: Bold Editorial Copy */}
          <div className="lg:col-span-6 space-y-8 text-left">
            
            <div className="inline-flex items-center space-x-2 bg-amber-500/10 border border-amber-500/20 px-3 py-1 rounded-full">
              <Award className="h-3.5 w-3.5 text-amber-500" />
              <span className="font-mono text-[9.5px] uppercase tracking-wider text-amber-400 font-bold">
                PROJETOS SELECIONADOS NO CASACOR 2025
              </span>
            </div>

            <div className="space-y-4">
              <h1 className="font-mono text-4xl sm:text-5xl md:text-6xl font-black text-white uppercase tracking-tight leading-[0.95]">
                Esculpindo <br />
                <span className="text-transparent bg-clip-text bg-gradient-to-r from-amber-400 via-yellow-500 to-stone-200">
                  Espaços Brutalistas
                </span> <br />
                E Autorais.
              </h1>
              <p className="font-sans text-sm md:text-base text-stone-400 leading-relaxed max-w-xl">
                Longe da mesmice das fachadas de condomínio fechado, o estúdio MÖBIUS cria arquitetura de vanguarda. Unimos a honestidade crua do concreto ripado, painéis de madeira natural e biofilia ativa para conceber lares que são verdadeiras esculturas de morar.
              </p>
            </div>

            {/* Micro layout bullet specs */}
            <div className="grid grid-cols-3 gap-4 border-y border-white/5 py-5">
              <div>
                <span className="font-mono text-2xl font-black text-white block">50+</span>
                <span className="font-mono text-[9px] uppercase text-stone-500 block">Projetos Executados</span>
              </div>
              <div className="border-x border-white/5 px-4">
                <span className="font-mono text-2xl font-black text-white block">12</span>
                <span className="font-mono text-[9px] uppercase text-stone-500 block">Prêmios Nacionais</span>
              </div>
              <div className="pl-4">
                <span className="font-mono text-2xl font-black text-white block">100%</span>
                <span className="font-mono text-[9px] uppercase text-stone-500 block">Acompanhamento Técnico</span>
              </div>
            </div>

            <div className="flex flex-col sm:flex-row gap-4">
              <a 
                href="#viabilidade"
                className="px-6 py-4 rounded-xl bg-white hover:bg-stone-100 text-black font-mono text-xs font-black tracking-wider uppercase transition-all duration-300 text-center flex items-center justify-center space-x-2 shadow-xl cursor-pointer"
              >
                <span>Iniciar Estudo de Custo</span>
                <Sliders className="h-4 w-4" />
              </a>
              <a 
                href="#obras"
                className="px-6 py-4 rounded-xl border border-white/10 hover:border-white/30 hover:bg-white/5 text-white font-mono text-xs font-bold tracking-wider uppercase transition-all text-center flex items-center justify-center space-x-1.5 cursor-pointer"
              >
                <span>Explorar Portfólio</span>
                <ChevronRight className="h-4 w-4" />
              </a>
            </div>

          </div>

          {/* Right Block: Luxury Hero Frame */}
          <div className="lg:col-span-6 relative">
            <div className="absolute -inset-1.5 bg-gradient-to-r from-amber-500/20 to-stone-900/50 rounded-2xl blur-xl opacity-70 pointer-events-none" />
            <div className="relative bg-[#0F1218] border border-white/10 rounded-2xl overflow-hidden p-3 shadow-2xl">
              <img 
                src={heroImg} 
                alt="Brutalist Concrete Residence Möbius" 
                referrerPolicy="no-referrer"
                className="w-full h-[320px] sm:h-[420px] object-cover rounded-xl grayscale hover:grayscale-0 transition-all duration-1000"
              />
              <div className="absolute bottom-6 left-6 right-6 p-4 rounded-xl bg-black/75 backdrop-blur-md border border-white/10 text-left space-y-1.5">
                <span className="font-mono text-[9px] text-amber-500 font-bold uppercase tracking-widest block">CASACOR DESTAQUE // CONCRETO RIPADO</span>
                <h4 className="font-mono text-sm font-black text-white uppercase tracking-tight">VILLA ATELIÊ DO BOSQUE</h4>
                <div className="flex items-center justify-between text-[10px] font-mono text-stone-400">
                  <span className="flex items-center gap-1"><MapPin className="h-3 w-3 text-amber-500" /> Campos do Jordão, SP</span>
                  <span>Área: 340 m²</span>
                </div>
              </div>
            </div>
          </div>

        </div>
      </section>

      {/* Filosofia Arquiteto Core Section */}
      <section className="py-24 bg-[#08090C] border-y border-white/5 relative" id="filosofia">
        <div className="max-w-7xl mx-auto px-6 md:px-12">
          <div className="text-center space-y-3 max-w-2xl mx-auto mb-16">
            <span className="font-mono text-xs text-amber-500 font-bold uppercase tracking-[0.25em] block">
              // ESSÊNCIA ARQUITETÔNICA
            </span>
            <h2 className="font-mono text-3xl md:text-4xl font-black text-white uppercase tracking-tight">
              Os Quatro Pilares Möbius
            </h2>
            <p className="font-sans text-sm text-stone-400">
              Acreditamos que cada linha traçada deve representar uma conexão íntima com a natureza e com a verdade estrutural dos materiais.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-4 gap-6 text-left">
            
            <div className="p-6 rounded-2xl bg-[#0E1116] border border-white/5 space-y-4 hover:border-amber-500/20 transition-all">
              <div className="h-10 w-10 bg-amber-500/10 border border-amber-500/20 rounded-lg flex items-center justify-center text-amber-500">
                <Layers className="h-5 w-5" />
              </div>
              <h3 className="font-mono text-sm font-black text-white uppercase tracking-wider">1. Honestidade Estrutural</h3>
              <p className="text-stone-400 text-xs sm:text-sm leading-relaxed">
                Não maquiamos pilares ou ocultamos vigas. O concreto, o aço e a pedra aparente são os ornamentos mais nobres de uma estrutura pura.
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-[#0E1116] border border-white/5 space-y-4 hover:border-amber-500/20 transition-all">
              <div className="h-10 w-10 bg-amber-500/10 border border-amber-500/20 rounded-lg flex items-center justify-center text-amber-500">
                <Trees className="h-5 w-5" />
              </div>
              <h3 className="font-mono text-sm font-black text-white uppercase tracking-wider">2. Biofilia Integrada</h3>
              <p className="text-stone-400 text-xs sm:text-sm leading-relaxed">
                Trazemos a floresta para dentro de casa. Jardins internos, pátios ensolarados e espelhos d'água integram a natureza no dia a dia.
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-[#0E1116] border border-white/5 space-y-4 hover:border-amber-500/20 transition-all">
              <div className="h-10 w-10 bg-amber-500/10 border border-amber-500/20 rounded-lg flex items-center justify-center text-amber-500">
                <Compass className="h-5 w-5" />
              </div>
              <h3 className="font-mono text-sm font-black text-white uppercase tracking-wider">3. Geometria Origami</h3>
              <p className="text-stone-400 text-xs sm:text-sm leading-relaxed">
                Brincamos com planos e dobras. Nossos balanços e coberturas criam um jogo de luz e sombra fascinante ao longo do decorrer do dia.
              </p>
            </div>

            <div className="p-6 rounded-2xl bg-[#0E1116] border border-white/5 space-y-4 hover:border-amber-500/20 transition-all">
              <div className="h-10 w-10 bg-amber-500/10 border border-amber-500/20 rounded-lg flex items-center justify-center text-amber-500">
                <Sliders className="h-5 w-5" />
              </div>
              <h3 className="font-mono text-sm font-black text-white uppercase tracking-wider">4. Eficiência Ativa</h3>
              <p className="text-stone-400 text-xs sm:text-sm leading-relaxed">
                Orientação solar perfeita, isolamento acústico premium e captação de água das chuvas. Luxo aliado ao respeito ecológico do amanhã.
              </p>
            </div>

          </div>
        </div>
      </section>

      {/* INTERACTIVE BEFORE & AFTER RENOVATION SLIDER (THE EXTREME CREATIVE STYLING PIECE) */}
      <section className="py-24 max-w-7xl mx-auto px-6 md:px-12 relative" id="antes-depois">
        
        {/* Visual helper markers */}
        <div className="absolute left-6 top-1/2 h-16 w-[1px] bg-white/10 hidden xl:block" />
        <div className="absolute right-6 top-1/2 h-16 w-[1px] bg-white/10 hidden xl:block" />

        <div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
          
          {/* Left info column */}
          <div className="lg:col-span-5 text-left space-y-6">
            <span className="font-mono text-xs text-amber-500 font-bold uppercase tracking-[0.2em] block">
              🕹️ INTERATIVO: ANTES & DEPOIS
            </span>
            <h2 className="font-mono text-3xl md:text-4xl font-black text-white uppercase tracking-tight">
              O Milagre da <br />Reconstrução
            </h2>
            <p className="font-sans text-sm text-stone-400 leading-relaxed">
              Reformar imóveis antigos exige respeito histórico e coragem estrutural. Use o controle deslizante à direita para revelar a metamorfose da <strong>Casa Itaim</strong>, onde transformamos uma estrutura antiga de tijolos vedados em um living brutalista aberto de tirar o fôlego.
            </p>
            
            <div className="space-y-4 pt-4 border-t border-white/5">
              <div className="flex items-center space-x-3 text-xs">
                <span className="h-6 w-12 bg-stone-700/60 border border-stone-600 text-stone-300 font-mono flex items-center justify-center rounded">ANTES</span>
                <span className="text-stone-400 font-sans">Quartos escuros divididos e pilares ocultados em alvenaria pesada.</span>
              </div>
              <div className="flex items-center space-x-3 text-xs">
                <span className="h-6 w-12 bg-amber-500/20 border border-amber-500/30 text-amber-400 font-mono flex items-center justify-center rounded font-bold">DEPOIS</span>
                <span className="text-stone-400 font-sans">Living integrado de pé-direito duplo com concreto e esquadrias infinitas.</span>
              </div>
            </div>

            {/* Quick manual percentage buttons for touch screens accessibility */}
            <div className="flex items-center space-x-2.5 pt-2">
              <span className="text-[10px] font-mono uppercase text-stone-500">Revelar:</span>
              <button 
                onClick={() => setSliderPosition(10)} 
                className="px-2.5 py-1 rounded bg-stone-900 border border-white/5 text-[10px] font-mono hover:text-amber-400 cursor-pointer"
              >
                90% Antes
              </button>
              <button 
                onClick={() => setSliderPosition(50)} 
                className="px-2.5 py-1 rounded bg-stone-900 border border-white/5 text-[10px] font-mono hover:text-amber-400 cursor-pointer"
              >
                Meio a Meio
              </button>
              <button 
                onClick={() => setSliderPosition(90)} 
                className="px-2.5 py-1 rounded bg-stone-900 border border-white/5 text-[10px] font-mono hover:text-amber-400 cursor-pointer"
              >
                90% Depois
              </button>
            </div>

          </div>

          {/* Right Visual Slider container */}
          <div className="lg:col-span-7">
            <div className="text-center mb-3">
              <span className="font-mono text-[10px] text-stone-500 uppercase">Arraste a linha central com o mouse ou dedo:</span>
            </div>
            
            <div 
              ref={sliderRef}
              onMouseMove={handleMouseMove}
              onTouchMove={handleTouchMove}
              onMouseDown={() => setIsDragging(true)}
              className="relative h-[280px] sm:h-[400px] rounded-2xl overflow-hidden border border-white/10 select-none cursor-ew-resize shadow-2xl"
            >
              
              {/* After Image (Full background) */}
              <img 
                src={livingImg} 
                alt="Depois Möbius Brutalista" 
                referrerPolicy="no-referrer"
                className="absolute inset-0 w-full h-full object-cover pointer-events-none"
              />
              <div className="absolute right-4 bottom-4 px-2.5 py-1.5 rounded-md bg-amber-500 text-black font-mono text-[10px] font-black z-20">
                DEPOIS // REFORMA MÖBIUS
              </div>

              {/* Before Image (Cropped container based on slider percentage position) */}
              <div 
                className="absolute inset-0 top-0 left-0 h-full overflow-hidden border-r-2 border-amber-500/80 z-10 pointer-events-none"
                style={{ width: `${sliderPosition}%` }}
              >
                <img 
                  src={beforeImg} 
                  alt="Antes Imóvel Antigo" 
                  referrerPolicy="no-referrer"
                  className="absolute inset-0 w-full h-full object-cover max-w-none pointer-events-none grayscale brightness-75"
                  style={{ width: sliderRef.current?.offsetWidth || "600px" }}
                />
                <div className="absolute left-4 bottom-4 px-2.5 py-1.5 rounded-md bg-black/80 text-stone-400 border border-white/10 font-mono text-[10px] font-bold">
                  ANTES DA REFORMA
                </div>
              </div>

              {/* Custom floating handles bar on the divider line */}
              <div 
                className="absolute top-0 bottom-0 w-[4px] bg-amber-500 z-30 pointer-events-none"
                style={{ left: `${sliderPosition}%` }}
              >
                <div className="absolute top-1/2 -left-4 -translate-y-1/2 h-9 w-9 rounded-full bg-amber-500 border-2 border-black flex items-center justify-center text-black font-bold shadow-lg shadow-amber-500/30">
                  ◀▶
                </div>
              </div>

            </div>
          </div>

        </div>
      </section>

      {/* INTERACTIVE MATERIAL MOODBOARD DESIGN WORKSHOP SECTION */}
      <section className="py-24 bg-[#080A0E] border-y border-white/5 relative" id="moodboard">
        
        <div className="max-w-7xl mx-auto px-6 md:px-12">
          
          <div className="text-center space-y-3 max-w-2xl mx-auto mb-16">
            <span className="font-mono text-xs text-amber-500 font-bold uppercase tracking-[0.25em] block">
              📐 ATELIÊ INTERATIVO DE INTERIORES
            </span>
            <h2 className="font-mono text-3xl md:text-4xl font-black text-white uppercase tracking-tight">
              Simulador de Moodboard Autoral
            </h2>
            <p className="font-sans text-sm text-stone-400">
              Combine texturas de concreto, pedras e madeiras nobres, ajuste a iluminação solar ou artificial e veja a ambientação e descrição técnica sugerida pelo arquiteto.
            </p>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-12 gap-10 items-stretch text-left">
            
            {/* Left: Interactive Material Toggles Panel */}
            <div className="lg:col-span-5 bg-[#0D1017] border border-white/5 rounded-2xl p-6 md:p-8 flex flex-col justify-between space-y-6">
              
              <div className="space-y-6">
                
                {/* Floor Material Customizer */}
                <div className="space-y-3">
                  <span className="font-mono text-[10px] text-amber-500 font-extrabold uppercase tracking-widest block flex items-center gap-1.5">
                    <Palette className="h-3.5 w-3.5" /> 01 // TEXTURA DE PISO:
                  </span>
                  <div className="grid grid-cols-3 gap-3">
                    {Object.entries(floorOptions).map(([key, opt]) => (
                      <button
                        key={key}
                        onClick={() => setSelectedFloor(key as any)}
                        className={`p-3 rounded-xl border text-left flex flex-col justify-between h-20 transition-all cursor-pointer ${
                          selectedFloor === key 
                            ? "border-amber-500 bg-amber-500/5" 
                            : "border-white/5 bg-[#121620] hover:border-white/10"
                        }`}
                      >
                        <div className={`h-4 w-4 rounded-full border ${opt.color}`} />
                        <span className="font-mono text-[10px] font-bold text-white uppercase leading-tight truncate">{opt.name.split(" ")[0]}</span>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Wall Coating Customizer */}
                <div className="space-y-3">
                  <span className="font-mono text-[10px] text-amber-500 font-extrabold uppercase tracking-widest block flex items-center gap-1.5">
                    <Hammer className="h-3.5 w-3.5" /> 02 // REVESTIMENTO DE PAREDE:
                  </span>
                  <div className="grid grid-cols-3 gap-3">
                    {Object.entries(wallOptions).map(([key, opt]) => (
                      <button
                        key={key}
                        onClick={() => setSelectedWall(key as any)}
                        className={`p-3 rounded-xl border text-left flex flex-col justify-between h-20 transition-all cursor-pointer ${
                          selectedWall === key 
                            ? "border-amber-500 bg-amber-500/5" 
                            : "border-white/5 bg-[#121620] hover:border-white/10"
                        }`}
                      >
                        <div className={`h-4 w-10 rounded border border-white/15 ${opt.texture}`} />
                        <span className="font-mono text-[10px] font-bold text-white uppercase leading-tight truncate">{opt.name.split(" ")[0]}</span>
                      </button>
                    ))}
                  </div>
                </div>

                {/* Light Customizer */}
                <div className="space-y-3">
                  <span className="font-mono text-[10px] text-amber-500 font-extrabold uppercase tracking-widest block flex items-center gap-1.5">
                    <Sun className="h-3.5 w-3.5" /> 03 // ILUMINAÇÃO & CENÁRIO:
                  </span>
                  <div className="grid grid-cols-3 gap-3">
                    {Object.entries(lightingOptions).map(([key, opt]) => {
                      const Icon = opt.icon;
                      return (
                        <button
                          key={key}
                          onClick={() => setSelectedLighting(key as any)}
                          className={`p-3 rounded-xl border text-left flex flex-col justify-between h-20 transition-all cursor-pointer ${
                            selectedLighting === key 
                              ? "border-amber-500 bg-amber-500/5" 
                              : "border-white/5 bg-[#121620] hover:border-white/10"
                          }`}
                        >
                          <Icon className={`h-4.5 w-4.5 ${selectedLighting === key ? "text-amber-500" : "text-stone-400"}`} />
                          <span className="font-mono text-[10px] font-bold text-white uppercase leading-tight truncate">{opt.name.split(" ")[0]}</span>
                        </button>
                      );
                    })}
                  </div>
                </div>

              </div>

              {/* Designer comment box */}
              <div className="p-4 bg-amber-500/5 border border-amber-500/10 rounded-xl space-y-1">
                <span className="text-[9px] font-mono uppercase text-amber-500 font-bold tracking-widest block">DIRETRIZ MÖBIUS STUDIO:</span>
                <p className="text-stone-400 text-xs font-sans leading-relaxed">
                  "Sempre combine no máximo três materiais estruturais predominantes. Menos ruído visual, mais impacto sensorial."
                </p>
              </div>

            </div>

            {/* Right: Dynamic Moodboard Hologram Frame */}
            <div className="lg:col-span-7 bg-[#0D1017] border border-white/5 rounded-2xl p-6 md:p-8 flex flex-col justify-between space-y-6 relative overflow-hidden">
              
              {/* Subtle tech background line drawings */}
              <div className="absolute right-0 top-0 w-24 h-24 border-r border-t border-white/5 pointer-events-none" />
              <div className="absolute left-0 bottom-0 w-24 h-24 border-l border-b border-white/5 pointer-events-none" />

              {/* Dynamic Moodboard Header */}
              <div className="flex items-center justify-between border-b border-white/5 pb-4 z-10">
                <div className="flex items-center space-x-2">
                  <span className="h-2 w-2 rounded-full bg-amber-500 animate-pulse" />
                  <span className="font-mono text-[10px] text-white/50 uppercase tracking-widest">GABARITO DE MATERIALIDADE DILUÍDO</span>
                </div>
                <span className="font-mono text-[10px] text-amber-500 uppercase font-black">
                  CENÁRIO ATIVO // {selectedLighting.toUpperCase()}
                </span>
              </div>

              {/* Dynamic render visual frame (changing colors and layouts depending on selection) */}
              <div className="my-4 p-4 rounded-xl border border-white/10 bg-black/40 min-h-[160px] grid grid-cols-1 sm:grid-cols-3 gap-4 items-center">
                
                {/* Floor visualizer blocks */}
                <div className="p-4 rounded-lg bg-[#121620] border border-white/5 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-[9px] text-stone-500">PISO</span>
                    <div className={`h-3 w-3 rounded-full ${floorOptions[selectedFloor].color}`} />
                  </div>
                  <h4 className="font-mono text-xs font-bold text-white uppercase">{floorOptions[selectedFloor].name.split(" ")[0]}</h4>
                  <p className="text-[11px] text-stone-400 leading-normal font-sans text-left">{floorOptions[selectedFloor].text}</p>
                </div>

                {/* Wall visualizer blocks */}
                <div className="p-4 rounded-lg bg-[#121620] border border-white/5 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-[9px] text-stone-500">PAREDE</span>
                    <div className={`h-2.5 w-6 rounded ${wallOptions[selectedWall].texture}`} />
                  </div>
                  <h4 className="font-mono text-xs font-bold text-white uppercase">{wallOptions[selectedWall].name.split(" ")[0]}</h4>
                  <p className="text-[11px] text-stone-400 leading-normal font-sans text-left">{wallOptions[selectedWall].text}</p>
                </div>

                {/* Lighting visualizer blocks */}
                <div className="p-4 rounded-lg bg-[#121620] border border-white/5 space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="font-mono text-[9px] text-stone-500">ILUMINAÇÃO</span>
                    {React.createElement(lightingOptions[selectedLighting].icon, { className: "h-3.5 w-3.5 text-amber-500" })}
                  </div>
                  <h4 className="font-mono text-xs font-bold text-white uppercase">{lightingOptions[selectedLighting].name.split(" ")[0]}</h4>
                  <p className="text-[11px] text-stone-400 leading-normal font-sans text-left">{lightingOptions[selectedLighting].text}</p>
                </div>

              </div>

              {/* Summary Description of the Atmosphere (Vibe) */}
              <div className="p-5 rounded-xl bg-black/40 border border-white/5 text-left space-y-3">
                <span className="font-mono text-[9px] text-amber-500 font-extrabold uppercase tracking-widest block">// ANÁLISE DO ESPAÇO HARMONIZADO:</span>
                <p className="text-stone-300 text-xs sm:text-sm font-sans leading-relaxed">
                  A combinação do piso <strong>{floorOptions[selectedFloor].name}</strong> com paredes revestidas de <strong>{wallOptions[selectedWall].name}</strong> sob a atmosfera de <strong>{lightingOptions[selectedLighting].name}</strong> gera uma estética singular. O calor orgânico contrapõe os elementos minerais frios, enquanto as sombras projetadas valorizam os encaixes ripados geométricos de forma escultural.
                </p>

                <div className="flex items-center space-x-3 text-[10px] font-mono text-stone-500 pt-2 border-t border-white/5">
                  <span>Isolamento Térmico: <strong className="text-white">Excelente</strong></span>
                  <span>•</span>
                  <span>Conforto Acústico: <strong className="text-white">85% Absorção</strong></span>
                  <span>•</span>
                  <span>Estilo: <strong className="text-amber-500">Möbius Premium</strong></span>
                </div>
              </div>

              {/* Quick WhatsApp Share option */}
              <button
                onClick={() => {
                  const txt = `Gostei do Moodboard: Piso ${floorOptions[selectedFloor].name}, Parede ${wallOptions[selectedWall].name}, Iluminação ${lightingOptions[selectedLighting].name}`;
                  window.open(`https://wa.me/5515997118125?text=${encodeURIComponent(txt)}`, "_blank");
                }}
                className="w-full py-3.5 rounded-xl bg-[#121620] hover:bg-[#1A202E] border border-white/10 hover:border-amber-500/50 text-white font-mono text-xs font-black uppercase tracking-wider transition-all duration-300 flex items-center justify-center space-x-2 cursor-pointer"
              >
                <span>Enviar este Moodboard para o Arquiteto</span>
                <ChevronRight className="h-4 w-4 text-amber-500" />
              </button>

            </div>

          </div>

        </div>
      </section>

      {/* FILTERABLE WORKS PORTFOLIO SHOWCASE */}
      <section className="py-24 max-w-7xl mx-auto px-6 md:px-12 relative" id="obras">
        
        <div className="flex flex-col md:flex-row justify-between items-start md:items-end gap-6 mb-16">
          <div className="text-left space-y-3">
            <span className="font-mono text-xs text-amber-500 font-bold uppercase tracking-[0.2em] block">
              // OBRAS SELECIONADAS MÖBIUS
            </span>
            <h2 className="font-mono text-3xl md:text-4xl font-black text-white uppercase tracking-tight">
              Nosso Portfólio de Linhas puras
            </h2>
          </div>

          {/* Filtering Toggles */}
          <div className="flex flex-wrap gap-2 bg-stone-900/50 p-1 rounded-xl border border-white/5 font-mono text-xs">
            {(["Todos", "Residencial", "Corporativo", "Interiores"] as const).map((cat) => (
              <button
                key={cat}
                onClick={() => setActiveCategory(cat)}
                className={`px-4 py-2 rounded-lg transition-all cursor-pointer ${
                  activeCategory === cat 
                    ? "bg-amber-500 text-black font-black" 
                    : "text-stone-400 hover:text-white"
                }`}
              >
                {cat}
              </button>
            ))}
          </div>
        </div>

        {/* Projects Cards Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 text-left">
          {filteredProjects.map((proj) => (
            <motion.div
              layout
              key={proj.id}
              className="bg-[#0E1116] border border-white/10 rounded-2xl overflow-hidden p-3.5 group flex flex-col justify-between h-full relative hover:border-amber-500/30 transition-all shadow-xl"
            >
              
              <div className="space-y-4">
                {/* Project Image Frame */}
                <div className="relative h-60 sm:h-72 w-full overflow-hidden rounded-xl bg-stone-950">
                  <img 
                    src={proj.image} 
                    alt={proj.title} 
                    referrerPolicy="no-referrer"
                    className="w-full h-full object-cover group-hover:scale-105 transition-all duration-700"
                  />
                  <div className="absolute top-4 right-4 px-2.5 py-1 rounded-md bg-black/80 backdrop-blur-md border border-white/10 font-mono text-[9px] font-bold text-amber-500 uppercase">
                    {proj.category}
                  </div>
                  <div className="absolute bottom-4 left-4 px-2.5 py-1 rounded-md bg-black/80 backdrop-blur-md border border-white/10 font-mono text-[9px] font-bold text-stone-300">
                    Ano: {proj.year}
                  </div>
                </div>

                {/* Info block */}
                <div className="space-y-2">
                  <div className="flex items-center space-x-1 text-stone-400 font-mono text-[10px]">
                    <MapPin className="h-3 w-3 text-amber-500" />
                    <span>{proj.location}</span>
                    <span>•</span>
                    <span>{proj.area}</span>
                  </div>
                  
                  <h3 className="font-mono text-lg font-black text-white uppercase tracking-tight group-hover:text-amber-400 transition-colors">
                    {proj.title}
                  </h3>
                  
                  <p className="font-sans text-xs sm:text-sm text-stone-400 leading-relaxed line-clamp-3">
                    {proj.description}
                  </p>
                </div>
              </div>

              {/* Expand Details button */}
              <div className="pt-4 border-t border-white/5 mt-4 flex items-center justify-between">
                <div className="flex flex-wrap gap-1">
                  {proj.materials.slice(0, 2).map((m, idx) => (
                    <span key={idx} className="font-mono text-[9px] text-stone-500 bg-stone-900 border border-white/5 px-2 py-0.5 rounded">
                      {m}
                    </span>
                  ))}
                </div>
                
                <button
                  onClick={() => setSelectedProject(proj)}
                  className="px-3.5 py-1.5 rounded bg-amber-500/10 hover:bg-amber-500 hover:text-black border border-amber-500/20 text-amber-400 font-mono text-[10px] font-bold uppercase transition-all flex items-center gap-1 cursor-pointer"
                >
                  <Eye className="h-3.5 w-3.5" />
                  <span>Ver Detalhes</span>
                </button>
              </div>

            </motion.div>
          ))}
        </div>

      </section>

      {/* PROJECT VIABILITY & COST ESTIMATOR (THE STAR VALUE INTERACTIVE PIECE) */}
      <section className="py-24 bg-[#08090C] border-y border-white/5 relative" id="viabilidade">
        
        {/* Subtle decorative target/grid in BG */}
        <div className="absolute left-0 right-0 top-0 bottom-0 pointer-events-none opacity-5 bg-[radial-gradient(#FFE600_1px,transparent_1px)] [background-size:24px_24px]" />

        <div className="max-w-4xl mx-auto px-6 md:px-12 relative z-10 text-left">
          
          <div className="text-center space-y-3 max-w-2xl mx-auto mb-16">
            <span className="font-mono text-xs text-amber-500 font-bold uppercase tracking-[0.25em] block">
              📊 CALCULADORA DE VIABILIDADE TÉCNICA
            </span>
            <h2 className="font-mono text-3xl md:text-4xl font-black text-white uppercase tracking-tight">
              Simule o Custo de Projeto Möbius
            </h2>
            <p className="font-sans text-sm text-stone-400">
              Planejar os custos e cronogramas de arquitetura e obra é essencial. Use nosso simulador exclusivo para estimar honorários de projeto Möbius, prazos e faixas globais de investimento.
            </p>
          </div>

          <div className="bg-[#0D1017] border border-white/10 rounded-3xl p-6 md:p-10 shadow-2xl grid grid-cols-1 md:grid-cols-12 gap-8 items-stretch relative overflow-hidden">
            
            {/* Soft background warning line glow */}
            <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-amber-500/5 via-amber-500 to-amber-500/5" />

            {/* Left: Input Selection Slider Controls */}
            <div className="md:col-span-7 space-y-6">
              
              {/* Build Area m² Slider */}
              <div className="space-y-2.5">
                <div className="flex justify-between items-center">
                  <label className="font-mono text-xs text-white/80 uppercase font-black tracking-wider">ÁREA TOTAL CONSTRUÍDA (M²)</label>
                  <span className="font-mono text-base font-black text-amber-500 bg-amber-500/10 px-2.5 py-0.5 rounded border border-amber-500/20">{area} m²</span>
                </div>
                <input 
                  type="range"
                  min="50"
                  max="1200"
                  step="10"
                  value={area}
                  onChange={(e) => setArea(Number(e.target.value))}
                  className="w-full h-2 bg-stone-900 border border-white/5 rounded-lg appearance-none cursor-pointer accent-amber-500"
                />
                <div className="flex justify-between text-[10px] font-mono text-stone-500">
                  <span>50 m² (Mínimo)</span>
                  <span>1.200 m² (Luxo Alto)</span>
                </div>
              </div>

              {/* Typology selection */}
              <div className="space-y-2.5">
                <label className="font-mono text-xs text-white/80 uppercase font-black tracking-wider block">TIPO DE PROPRIEDADE</label>
                <div className="grid grid-cols-3 gap-2">
                  {[
                    { key: "residencial", label: "Residencial", icon: Building2 },
                    { key: "comercial", label: "Comercial", icon: Briefcase },
                    { key: "interiores", label: "Interiores", icon: Palette },
                  ].map((item) => {
                    const Icon = item.icon;
                    return (
                      <button
                        key={item.key}
                        type="button"
                        onClick={() => setTypology(item.key as any)}
                        className={`p-3 rounded-xl border font-mono text-[10px] font-bold uppercase transition-all cursor-pointer flex flex-col items-center justify-center gap-1.5 ${
                          typology === item.key 
                            ? "border-amber-500 bg-amber-500/10 text-amber-400" 
                            : "border-white/5 bg-[#121620] text-stone-400 hover:border-white/10"
                        }`}
                      >
                        <Icon className="h-4.5 w-4.5" />
                        <span>{item.label}</span>
                      </button>
                    );
                  })}
                </div>
              </div>

              {/* Finish Level */}
              <div className="space-y-2.5">
                <label className="font-mono text-xs text-white/80 uppercase font-black tracking-wider block">PADRÃO DE ACABAMENTO & COMPLEXIDADE</label>
                <div className="grid grid-cols-3 gap-2">
                  {[
                    { key: "contemporaneo", label: "Contemporâneo", sub: "Clean & Fluido" },
                    { key: "atelie", label: "Ateliê Premium", sub: "Sob Medida" },
                    { key: "brutalista", label: "Brutalismo Puro", sub: "Estrutural Monumental" },
                  ].map((lvl) => (
                    <button
                      key={lvl.key}
                      type="button"
                      onClick={() => setFinishLevel(lvl.key as any)}
                      className={`p-2.5 rounded-xl border text-center transition-all cursor-pointer flex flex-col justify-between h-16 ${
                        finishLevel === lvl.key 
                          ? "border-amber-500 bg-amber-500/10 text-amber-400" 
                          : "border-white/5 bg-[#121620] text-stone-400 hover:border-white/10"
                      }`}
                    >
                      <span className="font-mono text-[10px] font-black uppercase leading-none block">{lvl.label}</span>
                      <span className="text-[8px] font-sans text-stone-500 block leading-none">{lvl.sub}</span>
                    </button>
                  ))}
                </div>
              </div>

              {/* Extras check tags */}
              <div className="space-y-2.5">
                <label className="font-mono text-xs text-white/80 uppercase font-black tracking-wider block">PROJETOS COMPLEMENTARES INCLUSOS</label>
                <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5">
                  <button
                    type="button"
                    onClick={() => setExtras(prev => ({ ...prev, automation: !prev.automation }))}
                    className={`p-3 rounded-xl border font-mono text-[9px] font-bold uppercase transition-all cursor-pointer flex items-center justify-between ${
                      extras.automation 
                        ? "border-amber-500 bg-amber-500/5 text-amber-400" 
                        : "border-white/5 bg-[#121620] text-stone-400"
                    }`}
                  >
                    <span className="flex items-center gap-1"><Cpu className="h-3.5 w-3.5" /> Automação</span>
                    <span className="h-4 w-4 bg-black/40 border border-white/10 flex items-center justify-center rounded text-[9px]">{extras.automation ? "✓" : ""}</span>
                  </button>

                  <button
                    type="button"
                    onClick={() => setExtras(prev => ({ ...prev, landscape: !prev.landscape }))}
                    className={`p-3 rounded-xl border font-mono text-[9px] font-bold uppercase transition-all cursor-pointer flex items-center justify-between ${
                      extras.landscape 
                        ? "border-amber-500 bg-amber-500/5 text-amber-400" 
                        : "border-white/5 bg-[#121620] text-stone-400"
                    }`}
                  >
                    <span className="flex items-center gap-1"><Trees className="h-3.5 w-3.5" /> Paisagismo</span>
                    <span className="h-4 w-4 bg-black/40 border border-white/10 flex items-center justify-center rounded text-[9px]">{extras.landscape ? "✓" : ""}</span>
                  </button>

                  <button
                    type="button"
                    onClick={() => setExtras(prev => ({ ...prev, lighting: !prev.lighting }))}
                    className={`p-3 rounded-xl border font-mono text-[9px] font-bold uppercase transition-all cursor-pointer flex items-center justify-between ${
                      extras.lighting 
                        ? "border-amber-500 bg-amber-500/5 text-amber-400" 
                        : "border-white/5 bg-[#121620] text-stone-400"
                    }`}
                  >
                    <span className="flex items-center gap-1"><Sun className="h-3.5 w-3.5" /> Luminotécnico</span>
                    <span className="h-4 w-4 bg-black/40 border border-white/10 flex items-center justify-center rounded text-[9px]">{extras.lighting ? "✓" : ""}</span>
                  </button>
                </div>
              </div>

            </div>

            {/* Right: Beautiful Price Estimate Result Gauge Card */}
            <div className="md:col-span-5 bg-black/50 border border-white/10 rounded-2xl p-6 flex flex-col justify-between space-y-6 relative">
              <div className="absolute top-4 right-4 h-3 w-3 rounded-full bg-amber-500 animate-pulse" />

              <div className="space-y-4">
                <span className="font-mono text-[9px] text-amber-500 font-bold uppercase tracking-widest block">
                  ESTUDO DE ORÇAMENTO COMPILADO // MÖBIUS
                </span>

                <div className="space-y-1">
                  <span className="text-[10px] font-mono text-stone-500 uppercase block">Projetos Executivos de Arquitetura:</span>
                  <div className="text-2xl sm:text-3xl font-mono font-black text-white">{estimateResult.designFee}</div>
                  <span className="text-[9px] font-mono text-stone-400 block">Faixa de Honorários {estimateResult.ratePerMeter} R$/m²</span>
                </div>

                <div className="h-[1px] bg-white/5" />

                <div className="space-y-1">
                  <span className="text-[10px] font-mono text-stone-500 uppercase block">Custo Estimado Global de Construção (Alvo):</span>
                  <div className="text-xl font-mono font-bold text-amber-400">{estimateResult.buildCost}</div>
                  <span className="text-[9px] font-sans text-stone-400 block leading-tight">Valor de referência de obra com base nos insumos atuais de concreto e alto padrão.</span>
                </div>

                <div className="h-[1px] bg-white/5" />

                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <span className="text-[9px] font-mono text-stone-500 block uppercase">Tempo de Projeto:</span>
                    <span className="text-sm font-mono font-bold text-white flex items-center gap-1 mt-0.5"><Clock className="h-4 w-4 text-amber-500" /> {estimateResult.months} Meses</span>
                  </div>
                  <div>
                    <span className="text-[9px] font-mono text-stone-500 block uppercase">Selo Ecológico:</span>
                    <span className="text-sm font-mono font-bold text-emerald-400 flex items-center gap-1 mt-0.5"><ShieldCheck className="h-4 w-4" /> LEED Apto</span>
                  </div>
                </div>

              </div>

              {/* Direct Booking and Pre-filled action */}
              <div className="space-y-3.5 pt-4 border-t border-white/10">
                <button
                  type="button"
                  onClick={shareToWhatsapp}
                  className="w-full py-4 rounded-xl bg-gradient-to-r from-amber-500 to-yellow-600 hover:from-yellow-600 hover:to-amber-500 text-black font-mono text-xs font-black tracking-wider uppercase transition-all duration-300 flex items-center justify-center space-x-2 shadow-lg cursor-pointer"
                >
                  <MessageSquare className="h-4.5 w-4.5 text-black" />
                  <span>Aprovar Estudo no WhatsApp</span>
                </button>
                <p className="text-[9px] font-sans text-stone-500 text-center leading-normal">
                  *Este simulador é uma ferramenta conceitual para balizar estudos preliminares. O custo final varia com a topografia exata e solo.
                </p>
              </div>

            </div>

          </div>

        </div>
      </section>

      {/* DETAILED PROJECT INFO EXPAND MODAL */}
      <AnimatePresence>
        {selectedProject && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 bg-black/95 backdrop-blur-md flex items-center justify-center z-50 p-4 sm:p-6"
          >
            <motion.div
              initial={{ scale: 0.9, y: 20 }}
              animate={{ scale: 1, y: 0 }}
              exit={{ scale: 0.9, y: 20 }}
              className="bg-[#0D1017] border border-white/10 rounded-2xl max-w-3xl w-full p-6 md:p-8 space-y-6 relative text-left max-h-[90vh] overflow-y-auto"
            >
              
              {/* Close Button */}
              <button
                onClick={() => setSelectedProject(null)}
                className="absolute top-4 right-4 h-9 w-9 bg-stone-900 border border-white/15 rounded-full flex items-center justify-center text-white/60 hover:text-white cursor-pointer"
              >
                ✕
              </button>

              <div className="space-y-4">
                <span className="font-mono text-xs text-amber-500 font-bold uppercase tracking-widest">{selectedProject.category} // DETALHAMENTO DE OBRA</span>
                <h3 className="font-mono text-2xl font-black text-white uppercase tracking-tight">{selectedProject.title}</h3>
                
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 bg-black/40 border border-white/5 p-4 rounded-xl font-mono text-xs text-stone-400">
                  <div>
                    <span className="block text-stone-500 text-[10px] uppercase">Localização:</span>
                    <strong className="text-white mt-0.5 block">{selectedProject.location}</strong>
                  </div>
                  <div>
                    <span className="block text-stone-500 text-[10px] uppercase">Ano de Projeto:</span>
                    <strong className="text-white mt-0.5 block">{selectedProject.year}</strong>
                  </div>
                  <div>
                    <span className="block text-stone-500 text-[10px] uppercase">Área Construída:</span>
                    <strong className="text-white mt-0.5 block">{selectedProject.area}</strong>
                  </div>
                  <div>
                    <span className="block text-stone-500 text-[10px] uppercase">Garantia Técnica:</span>
                    <strong className="text-emerald-400 mt-0.5 block">5 Anos Integral</strong>
                  </div>
                </div>

                <div className="relative h-64 sm:h-80 w-full rounded-xl overflow-hidden bg-stone-950 border border-white/10">
                  <img 
                    src={selectedProject.image} 
                    alt={selectedProject.title} 
                    referrerPolicy="no-referrer"
                    className="w-full h-full object-cover"
                  />
                </div>

                <div className="space-y-3">
                  <h4 className="font-mono text-xs font-black text-white uppercase tracking-wider flex items-center gap-1">
                    <FileText className="h-4 w-4 text-amber-500" /> CONCEITO ARQUITETÔNICO & RESOLUÇÃO TÉCNICA:
                  </h4>
                  <p className="font-sans text-xs sm:text-sm text-stone-300 leading-relaxed">
                    {selectedProject.description}
                  </p>
                  <p className="font-sans text-xs sm:text-sm text-stone-400 italic bg-amber-500/5 border-l-2 border-amber-500 p-3.5">
                    <strong>Diretriz Autoral:</strong> {selectedProject.concept}
                  </p>
                </div>

                <div className="space-y-2">
                  <h4 className="font-mono text-xs font-bold text-white uppercase">MATERIAIS E ACABAMENTOS ESPECIFICADOS:</h4>
                  <div className="flex flex-wrap gap-2">
                    {selectedProject.materials.map((mat, idx) => (
                      <span key={idx} className="font-mono text-xs text-amber-400 bg-amber-500/10 border border-amber-500/20 px-3 py-1 rounded-full font-bold">
                        {mat}
                      </span>
                    ))}
                  </div>
                </div>

              </div>

              {/* Action buttons inside modal */}
              <div className="pt-4 border-t border-white/10 flex flex-col sm:flex-row gap-4">
                <a
                  href={`https://wa.me/5515997118125?text=Gostei%20do%20projeto%20${encodeURIComponent(selectedProject.title)}`}
                  target="_blank"
                  rel="noreferrer"
                  className="px-6 py-3.5 rounded-xl bg-gradient-to-r from-amber-500 to-yellow-600 text-black font-mono text-xs font-black uppercase tracking-wider text-center flex-1 transition-all flex items-center justify-center space-x-1.5 cursor-pointer"
                >
                  <Phone className="h-4 w-4" />
                  <span>Quero Projeto Semelhante</span>
                </a>
                <button
                  type="button"
                  onClick={() => setSelectedProject(null)}
                  className="px-6 py-3.5 rounded-xl border border-white/10 hover:border-white/20 text-white/70 font-mono text-xs font-bold text-center cursor-pointer"
                >
                  Voltar para Projetos
                </button>
              </div>

            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* CORE CAPTURE / CONTACT & videoconference FORM */}
      <section className="py-24 max-w-4xl mx-auto px-6 md:px-12 relative" id="contato">
        <div className="bg-[#0E1116] border border-white/10 rounded-3xl p-6 md:p-10 text-left space-y-8 relative overflow-hidden shadow-2xl">
          
          <div className="absolute -right-24 -bottom-24 w-48 h-48 bg-amber-500/5 rounded-full blur-3xl pointer-events-none" />

          <div className="space-y-3">
            <span className="font-mono text-xs text-amber-500 font-bold uppercase tracking-widest block flex items-center gap-1.5">
              <Mail className="h-4 w-4" /> CONEXÃO DIRETA // BRIEFING
            </span>
            <h2 className="font-mono text-2xl md:text-3xl font-black text-white uppercase tracking-tight">
              Agende Seu Estudo de Implantação
            </h2>
            <p className="font-sans text-xs sm:text-sm text-stone-400 leading-relaxed">
              Damos vida à sua obra. Conte-nos brevemente o que você está planejando (residência, comercial, reforma ou interiores) para agendarmos uma videoconferência de alinhamento com nosso arquiteto autor.
            </p>
          </div>

          {!formSubmitted ? (
            <form onSubmit={handleLeadSubmit} className="space-y-4">
              
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                
                <div className="space-y-1.5">
                  <label className="font-mono text-[10px] text-stone-400 uppercase font-bold">Seu Nome Completo:</label>
                  <input 
                    type="text" 
                    required
                    value={formData.name}
                    onChange={(e) => setFormData(prev => ({ ...prev, name: e.target.value }))}
                    placeholder="Ex: Carlos Albuquerque"
                    className="w-full bg-[#121620] border border-white/10 rounded-xl px-4 py-3 text-white text-xs sm:text-sm focus:border-amber-500 outline-none transition-all"
                  />
                </div>

                <div className="space-y-1.5">
                  <label className="font-mono text-[10px] text-stone-400 uppercase font-bold">Seu WhatsApp de Contato:</label>
                  <input 
                    type="tel" 
                    required
                    value={formData.phone}
                    onChange={(e) => setFormData(prev => ({ ...prev, phone: e.target.value }))}
                    placeholder="Ex: (11) 99999-9999"
                    className="w-full bg-[#121620] border border-white/10 rounded-xl px-4 py-3 text-white text-xs sm:text-sm focus:border-amber-500 outline-none transition-all"
                  />
                </div>

              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                
                <div className="space-y-1.5">
                  <label className="font-mono text-[10px] text-stone-400 uppercase font-bold">E-mail para Envio de PDF:</label>
                  <input 
                    type="email" 
                    required
                    value={formData.email}
                    onChange={(e) => setFormData(prev => ({ ...prev, email: e.target.value }))}
                    placeholder="Ex: carlos@empresa.com.br"
                    className="w-full bg-[#121620] border border-white/10 rounded-xl px-4 py-3 text-white text-xs sm:text-sm focus:border-amber-500 outline-none transition-all"
                  />
                </div>

                <div className="space-y-1.5">
                  <label className="font-mono text-[10px] text-stone-400 uppercase font-bold">Orçamento Estimado para Obra:</label>
                  <select
                    value={formData.estimatedBudget}
                    onChange={(e) => setFormData(prev => ({ ...prev, estimatedBudget: e.target.value }))}
                    className="w-full bg-[#121620] border border-white/10 rounded-xl px-4 py-3 text-white text-xs sm:text-sm focus:border-amber-500 outline-none transition-all cursor-pointer"
                  >
                    <option value="r$ 200k - 500k">R$ 200.000 a R$ 500.000</option>
                    <option value="r$ 500k - 1.5M">R$ 500.000 a R$ 1.500.000</option>
                    <option value="r$ 1.5M+">Acima de R$ 1.500.000 (Luxo Brutalista)</option>
                  </select>
                </div>

              </div>

              <div className="space-y-1.5">
                <label className="font-mono text-[10px] text-stone-400 uppercase font-bold">Descreva a Ideia do Seu Projeto (M²) ou Terreno:</label>
                <textarea 
                  rows={4}
                  required
                  value={formData.about}
                  onChange={(e) => setFormData(prev => ({ ...prev, about: e.target.value }))}
                  placeholder="Ex: Gostaria de construir uma casa térrea de concreto ripado de aproximadamente 300 m² em um terreno em declive com vista..."
                  className="w-full bg-[#121620] border border-white/10 rounded-xl p-4 text-white text-xs sm:text-sm focus:border-amber-500 outline-none transition-all resize-none"
                />
              </div>

              {/* Submit CTA button */}
              <button
                type="submit"
                className="w-full py-4 rounded-xl bg-gradient-to-r from-amber-500 to-yellow-600 hover:from-yellow-600 hover:to-amber-500 text-black font-mono text-xs font-black tracking-widest uppercase transition-all duration-300 transform hover:scale-[1.01] flex items-center justify-center space-x-2 shadow-lg shadow-amber-500/10 cursor-pointer"
              >
                <span>Aprovar Estudo & Agendar Videoconferência</span>
                <Check className="h-4.5 w-4.5 text-black" />
              </button>

            </form>
          ) : (
            // Form success card
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              className="py-10 text-center space-y-6"
            >
              <div className="h-16 w-16 bg-emerald-500/10 border border-emerald-500/30 rounded-full flex items-center justify-center text-emerald-400 mx-auto">
                <Check className="h-8 w-8" />
              </div>

              <div className="space-y-2">
                <h3 className="font-mono text-xl sm:text-2xl font-black text-white uppercase">BRIEFING RECEBIDO COM SUCESSO! 🎉</h3>
                <p className="font-sans text-xs sm:text-sm text-stone-400 max-w-lg mx-auto">
                  Olá, <strong>{formData.name}</strong>. Nosso arquiteto-chefe já recebeu seus detalhes do projeto de {area} m² e orçamento estimado de {formData.estimatedBudget.toUpperCase()}.
                </p>
                <p className="font-sans text-xs text-stone-400 max-w-lg mx-auto">
                  Enviaremos em instantes um e-mail para <strong>{formData.email}</strong> com nossa cartilha técnica em PDF de implantação.
                </p>
              </div>

              <div className="flex flex-col sm:flex-row gap-4 justify-center max-w-md mx-auto pt-4">
                <button
                  type="button"
                  onClick={shareToWhatsapp}
                  className="px-6 py-4 rounded-xl bg-gradient-to-r from-amber-500 to-yellow-600 hover:from-yellow-600 hover:to-amber-500 text-black font-mono text-xs font-black tracking-wider uppercase transition-all duration-300 flex items-center justify-center gap-1.5 cursor-pointer flex-1"
                >
                  <Phone className="h-4 w-4" />
                  <span>Acelerar no WhatsApp</span>
                </button>
                
                <button
                  type="button"
                  onClick={() => {
                    setFormSubmitted(false);
                    setFormData({ name: "", email: "", phone: "", about: "", estimatedBudget: "r$ 200k - 500k" });
                  }}
                  className="px-5 py-4 rounded-xl border border-white/10 bg-white/5 text-stone-300 font-mono text-xs font-bold transition-all hover:bg-white/10 cursor-pointer"
                >
                  Enviar Outra Ideia
                </button>
              </div>

            </motion.div>
          )}

        </div>
      </section>

      {/* Retro/Brutalist Small Footer */}
      <footer className="py-12 border-t border-white/5 bg-[#050608]">
        <div className="max-w-7xl mx-auto px-6 md:px-12 flex flex-col sm:flex-row items-center justify-between gap-6 text-[11px] font-mono text-stone-500">
          <div className="flex items-center space-x-2">
            <Compass className="h-4 w-4 text-amber-500" />
            <span>© {new Date().getFullYear()} MÖBIUS STUDIO DE ARQUITETURA. TODOS OS DIREITOS RESERVADOS.</span>
          </div>
          <div className="flex space-x-6">
            <span>SÃO PAULO</span>
            <span>•</span>
            <span>CAMPOS DO JORDÃO</span>
            <span>•</span>
            <span>MILÃO</span>
          </div>
        </div>
      </footer>

    </div>
  );
}
